import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import "./globals.css";
import { QueryProviders } from "@/provider/query-provider";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";

const fontInter = Inter({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

type RootLayoutProps = {
	children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
	return (
		<html lang="en">
			<body className={cn(fontInter.className, "antialiased min-h-screen")}>
				<QueryProviders>
					<NuqsAdapter>
						<Toaster />
						{children}
					</NuqsAdapter>
				</QueryProviders>
			</body>
		</html>
	);
}
